### ISSUE TITLE
Nvim will crash when meet large python project like pytorch

### ISSUE THREAD

**Issue by LLMChild** [artemave/workspace-diagnostics.nvim#10]
## Description

when I open large python project, nvim crashed. It works well when I disable workspace-diagnostics.nvim

## Steps to reproduce

1. I did the command `nvim pytorch`
2. Then I saw `nvim is stuck`
3. LSP will throw Error after a quite long time 

## Environment

- Neovim version: 0.10.0
- workspace-diagnostics version: [latest]
- Plugin clash: [lsp diagnostic]

**Comment by LLMChild** [comment]
Maybe add an argument specifying the maximum number of files need diagnostics in the workspace.
Maybe index top-k file here: https://github.com/artemave/workspace-diagnostics.nvim/blob/0f0dad6cc3fbc2c9c2d850eb7611917cf66d4595/lua/workspace-diagnostics/init.lua#L107

**Comment by artemave** [comment]
> Maybe add an argument specifying the maximum number of files need diagnostics in the workspace. 

Btw, you can already supply your own `workspace_files` function in options.

**Comment by artemave** [comment]
What is puzzling me is why nvim grags down and halts, given all those lsp calls are asynchronous.

**Comment by artemave** [comment]
I pushed a couple of commits that are supposed to speed things up. May not be relevant to your case, but give it a spin.

**Comment by LLMChild** [comment]
> > Maybe add an argument specifying the maximum number of files need diagnostics in the workspace.
> 
> Btw, you can already supply your own `workspace_files` function in options.

Yes, I have already tried this, and it worked, but it seems irrelevant with my problems.
But from the LSP log, it seems that lsp crashed for some reason I can not understand, and it happens for a lot of files.
So when I use workspace-diagnostics, these files make lsp crashed again and again.
It seems irrelevant with workspace diagnostics.

**Comment by LLMChild** [comment]
> I pushed a couple of commits that are supposed to speed things up. May not be relevant to your case, but give it a spin.

Great work, I will update it right now,
