### ISSUE TITLE
Hangs the entire system

### ISSUE THREAD

**Issue by duarm** [artemave/workspace-diagnostics.nvim#11]
## Description

Opening a medium=sized C project with this hangs my system, all cores at 100%, until the process is killed by the OS. I'm using clangd. Not sure if this is due to a conflict with another plugin or some configuration problem. But after disabling the workspace-diagnostics.nvim, everything works as expected.

## Steps to reproduce

1. Open a properly configured medium/large project with clangd and this plugin.

## Environment

- NVIM v0.11.0-dev-337+g4b3be56a03
- Plugin: dev

**Comment by artemave** [comment]
Yeah, it's kinda bound to happen. What is "medium-sized"? How many files?

**Comment by duarm** [comment]
```
$ git ls-files | wc -l         
250
```

Mostly dependencies I keep in source, so an easy way to exclude folders would go a long way

**Comment by artemave** [comment]
> an easy way to exclude folders would go a long way

[There is one](https://github.com/artemave/workspace-diagnostics.nvim?tab=readme-ov-file#-configuration) actually:

```lua
require("workspace-diagnostics").setup({
  workspace_files = function()
    return { 'index.js', 'lib/banana.js' }
  end
})
```
