### ISSUE TITLE
After setting up the plugin, tsserver keeps initializing then crashes

### ISSUE THREAD

**Issue by belizar** [artemave/workspace-diagnostics.nvim#13]
## Description

I am in a Turbo monorepo configuration with three NextJS apps and two packages, is not a very large project.
After I setup the plugin, I can see the errors for the entire workspace, but two things happens, the first one is the I feel Neovim going slowly than before, and the second one is the tsserver initialise and crash for some reason, and keeps doing it in a loop until definitively crashes. 

## Steps to reproduce

I just followed the steps in the README. Here are some screenshots with what is happening.
I cannot share my repo because is a client's one.

<img width="440" alt="image" src="https://github.com/user-attachments/assets/c916e90d-16c0-4031-a5ed-dcc20b67a589">
<img width="724" alt="image" src="https://github.com/user-attachments/assets/95379e7e-963a-4c41-bad7-cc688c83bc4c">

## Expected behavior

It have to work as expected

## Environment

- Neovim version: [0.10.0]
- workspace-diagnostics version: [latest]
- Plugin clash: [tsserver]

**Comment by artemave** [comment]
Yeah it's hard to say... One thing to check possibly is the list of project files? If for whatever reason it includes `node_modules` then maybe even a small project can get prohibitively large. The default file is the output of `git ls-files`.
