### ISSUE TITLE
It doesn't seem to work with eslint

### ISSUE THREAD

**Issue by bezlant** [artemave/workspace-diagnostics.nvim#14]
Hi, 
It doesn't seem to work for me with eslint
I've tried to debug it, it correctly finds all the files, sends the didChange event, but the diagnostics simply don't in Trouble diagnostics.
My settings below, config in below
https://github.com/bezlant/nvim/commit/7ff9689ec98dbe6f842d7d2cc17f7ce74bce31c1

**Comment by bezlant** [comment]
the files linted are .ts or .tsx, so i suspect it could be related to the old issues

**Comment by artemave** [comment]
If you see that `textDocument/didOpen` is being sent to eslint lsp server, then I am out of ideas. After this point, it's supposed to just work - the server sends back diagnostics.

**Comment by bezlant** [comment]
Well, I'm able to check the client.notify return code and it returns true, which supposed to mean success (as for the nvim api)

**Comment by bezlant** [comment]
Maybe there are other ways to get to the root of the issue?
