### ISSUE TITLE
It works, but disables other lsp functionality

### ISSUE THREAD

**Issue by einarpersson** [artemave/workspace-diagnostics.nvim#15]
## Description

Hi! Thanks for this very promising little plugin. The plugin works as intended but existing LSP functionality seems to be disabled

## Steps to reproduce

I added the following
```lua
lspconfig.svelte.setup({
  on_attach = function(client, bufnr)
    require("workspace-diagnostics").populate_workspace_diagnostics(client, bufnr)
  end
})
```

I opened a svelte file.

Existing LSP stuff like showing defintions etc. did not work any longer. But the diagnostics list was populated!

I also tried
```lua
lspconfig.svelte.setup({
  on_attach = function(client, bufnr)
    if lspconfig.util.default_config.on_attach then
      lspconfig.util.default_config.on_attach(client, bufnr)
    end

    require("workspace-diagnostics").populate_workspace_diagnostics(client, bufnr)
  end
})
```
but no difference

## Expected behavior

I expect no side effects.

I am fairly new to Neovim, so I'd prefer if there is a complete working setup example instead of `...` and assuming that the reader knows what should be there.

## Environment

- Neovim version: NVIM v0.9.5
- workspace-diagnostics version: latest

**Comment by einarpersson** [comment]
Okey, so I found some info here which was very relevant to my case

https://github.com/neovim/nvim-lspconfig?tab=readme-ov-file#troubleshooting

**Comment by banjerluke** [comment]
@einarpersson I'm struggling with the same issue. Did you manage to solve it for yourself? I've looked at the troubleshooting link but I'm still at a loss. I have `workspace-diagnostics.nvim` triggered by a keybinding, i.e. not autorunning, but it still breaks Svelte's LSP...

**Comment by banjerluke** [comment]
Sorry, nevermind. It appears that it was an issue with my `tsconfig.json`'s `paths` config. Still no idea why it stopped working right when I installed this plugin, but my issue was unrelated to `workspace-diagnostics.nvim`.
