### ISSUE TITLE
Undefined global `map`.

### ISSUE THREAD

**Issue by sidke** [artemave/workspace-diagnostics.nvim#2]
Plugin doesn't work with fresh install, narrowed it down to:
https://github.com/artemave/workspace-diagnostics.nvim/blob/ed04f40ec2ca55a9dab42ef0e4d3e7b655b752cd/lua/workspace-diagnostics/init.lua#L38

I might be missing something but it looks to want to be `vim.tbl_map` instead:

```
    _workspace_files = vim.tbl_map(function(path)
      return vim.fn.fnamemodify(path, ":p")
    end, _workspace_files)
```

**Comment by artemave** [comment]
Ah. I happen to have `map` defined somewhere down in my init files 🤦
