### ISSUE TITLE
Doesn't find errors / react on changes except oppened buffers

### ISSUE THREAD

**Issue by MironPascalCaseFan** [artemave/workspace-diagnostics.nvim#7]
## Description

I recorded video of my issue:
https://drive.google.com/drive/folders/1BT9gN4lYgKCO2lsD3Q8er95HfUa1F_N2

## Expected behavior
All errors after changing the file in the workspace should be found without restarting the nvim, or at least after restarting the Lsp

(I use autowriteall)

**Comment by artemave** [comment]
I have no idea what's going on in that video. Could you please describe the problem in writing?

**Comment by miron2363** [comment]
Oh, I'm sorry, this is probably a problem in the lsp, not in the plugin. My problem is that lsp does not respond to changes in other files
For example.

**Comment by miron2363** [comment]
Oh, I'm sorry, this is probably a problem in the lsp, not in the plugin. 

My problem is that lsp does not react to changes in other files until I restart nvim and open file again
Look at this example
I have three files
main.cpp
other.cpp
other.hpp
I use function declared in other.hpp 
and implemented in other.cpp
![Снимок экрана 2024-04-26 002257](https://github.com/artemave/workspace-diagnostics.nvim/assets/80050619/f06ae911-31cf-4972-8e8f-d134182ca5f6)

if I delete declaration in other.hpp
Lsp doesn't tell me about error
![Снимок экрана 2024-04-26 002313](https://github.com/artemave/workspace-diagnostics.nvim/assets/80050619/d743a892-410d-479c-8ab6-fcf3436ad5d1)

It is tell me about error only after restart
nvim and open main.cpp again
![Снимок экрана 2024-04-26 002403](https://github.com/artemave/workspace-diagnostics.nvim/assets/80050619/f022da7a-0dc0-4a3c-a6f9-ebe6cc2c7d07)

**Comment by MironPascalCaseFan** [comment]
look at this example
![Снимок экрана 2024-04-26 002257](https://github.com/artemave/workspace-diagnostics.nvim/assets/80050619/ca559993-3103-4f96-a0fe-3a98a8669e86)


I have a project with these three files
main.cpp
other.cpp
other.hpp

I declare function in other.hpp and implement in other.cpp
And then I include other.hpp in main.cpp and use this function there
I can run nvim by openning other.hpp and delete declaration of this function
Now I expect what when I open diagnostics through a telescope being in other.hpp I will see an error in main.cpp. But this is not happening

Am I demanding something too much?

I forgot to mention that I will  see the error when entering the diagnostics through the telescope, but only on condition that I first opened main.cpp , then I will go to other.hpp and comment/delete the definition

**Comment by MironPascalCaseFan** [comment]
Oh, after I made git init and added the project files to it, everything works as I wanted from the very beginning. (Also i need save changes in file manually because it doesn’t react on autowriteall option for some reason (The fact that I was relying on autowriteall was a problem in the first video and In my previous comment, the problem was that I didn't have git in the project)). 

It was necessary to take a closer look at how it works in your post at README. 

Thanks for the great plugin!
